
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'commandeNUMBER ID OPBIN LPAREN RPAREN LACO RACO END AFFECT COMMA FINISH MAIN IF RETURN WHILE PRINTprogramme : MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO\n    enum : ID\n              | ID COMMA enum\n    empty :commande : ID AFFECT expression\n                  | commande END commande\n                  | WHILE LPAREN expression RPAREN LACO commande RACOexpression :  NUMBER\n                    | ID\n                    | expression OPBIN expression'
    
_lr_action_items = {'OPBIN':([7,8,9,10,14,],[-9,12,-8,12,12,]),'END':([3,7,8,9,11,14,16,17,],[6,-9,-5,-8,6,-10,6,-7,]),'RACO':([7,8,9,11,14,16,17,],[-9,-5,-8,-6,-10,17,-7,]),'LPAREN':([2,],[5,]),'ID':([0,4,5,6,12,15,],[1,7,7,1,7,1,]),'WHILE':([0,6,15,],[2,2,2,]),'LACO':([13,],[15,]),'$end':([3,7,8,9,11,14,17,],[0,-9,-5,-8,-6,-10,-7,]),'AFFECT':([1,],[4,]),'RPAREN':([7,9,10,14,],[-9,-8,13,-10,]),'NUMBER':([4,5,12,],[9,9,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([4,5,12,],[8,10,14,]),'commande':([0,6,15,],[3,11,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commande","S'",1,None,None,None),
  ('programme -> MAIN LPAREN enum RPAREN LACO commande FINISH PRINT LPAREN expression RPAREN RACO','programme',12,'p_programme','compilateur.py',83),
  ('enum -> ID','enum',1,'p_enum','compilateur.py',92),
  ('enum -> ID COMMA enum','enum',3,'p_enum','compilateur.py',93),
  ('empty -> <empty>','empty',0,'p_empty','compilateur.py',102),
  ('commande -> ID AFFECT expression','commande',3,'p_commande','compilateur.py',105),
  ('commande -> commande END commande','commande',3,'p_commande','compilateur.py',106),
  ('commande -> WHILE LPAREN expression RPAREN LACO commande RACO','commande',7,'p_commande','compilateur.py',107),
  ('expression -> NUMBER','expression',1,'p_expression','compilateur.py',123),
  ('expression -> ID','expression',1,'p_expression','compilateur.py',124),
  ('expression -> expression OPBIN expression','expression',3,'p_expression','compilateur.py',125),
]
